---
name: Trigger specific package build

on:
  workflow_dispatch:
    inputs:
      product:
        description: Product to build
        type: choice
        options:
        - authoritative
        - recursor
        - dnsdist
      os:
        description: OSes to build for, space separated
        type: string
        # please remember to update build-packages.yml as well
        default: >
          el-7
          el-8
          el-9
          debian-buster
          debian-bullseye
          debian-bookworm
          ubuntu-focal
          ubuntu-jammy
      ref:
        description: git ref to checkout
        type: string
        default: master
      is_release:
        description: is this a release build?
        type: choice
        options:
        - 'NO'
        - 'YES'

jobs:
  call-build-packages:
    uses: omoerbeek/pdns/.github/workflows/build-packages.yml@rec-rusttest
    with:
      product: ${{ github.event.inputs.product }}
      os: ${{ github.event.inputs.os }}
      ref: ${{ github.event.inputs.ref }}
      is_release: ${{ github.event.inputs.is_release }}
    secrets:
      DOWNLOADS_AUTOBUILT_SECRET: ${{ secrets.DOWNLOADS_AUTOBUILT_SECRET }}
      DOWNLOADS_AUTOBUILT_RSYNCTARGET: ${{ secrets.DOWNLOADS_AUTOBUILT_RSYNCTARGET }}
      DOWNLOADS_AUTOBUILT_HOSTKEY: ${{ secrets.DOWNLOADS_AUTOBUILT_HOSTKEY }}
